spring:
  application:
    name: discovery-server
server:
  port: 8083

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8082/eureka
  instance:
    hostname: localhost